# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/vike-vue/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore: '

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'

    # Avoid mismatching versions between vike-vue and examples for these
    # dependencies:
    ignore:
      - dependency-name: 'vite-plugin-ssr'

  - package-ecosystem: 'npm'
    directory: '/examples/basic/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore: '

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'

    # Avoid mismatching versions between vike-vue and examples for these
    # dependencies:
    ignore:
      - dependency-name: 'vite-plugin-ssr'

  - package-ecosystem: 'npm'
    directory: '/examples/ssr-spa/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore: '

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'

    # Avoid mismatching versions between vike-vue and examples for these
    # dependencies:
    ignore:
      - dependency-name: 'vite-plugin-ssr'

  - package-ecosystem: 'npm'
    directory: '/examples/with-vue-plugin/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore: '

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'

    # Avoid mismatching versions between vike-vue and examples for these
    # dependencies:
    ignore:
      - dependency-name: 'vite-plugin-ssr'
