name: CI
on:
  - push
  - pull_request

jobs:
  build:
    name: Build on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build vike-vue
        run: pnpm run build

      - name: Build example basic
        run: pnpm run build
        working-directory: ./examples/basic

      - name: Build example ssr-spa
        run: pnpm run build
        working-directory: ./examples/ssr-spa
